# Site settings
title: Jiang's Blog
header-img: img/home-bg.jpg
email: yeah.jiang@mail.utoronto.ca
description: "Blog for AngularJS, Django, Wordpress and web development related content."
baseurl: ""
url: "http://icebeary.github.io"
# twitter_username: SBootstrap
github_username:  IceBeary
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
